import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Button from "@/components/button";

const inter = Inter({ subsets: ["latin"] });
const plus_Jakarta_Sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GetchFoods",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-16 shadow-lg flex items-center justify-between px-6">
          <span className={`${plus_Jakarta_Sans.className} font-bold text-lg`}>
            GetchFoods
          </span>
          <Button href="/sign-in">Masuk</Button>
        </header>
        {children}
      </body>
    </html>
  );
}
